### ISSUE TITLE
Internal Server Error for music map: 12months + overall 

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [smcgivern/last-fm-music-mapper#1]
I. 
e.g. these work for me:
http://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/7day/
http://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/6month/

II. but I get "Internal Server Error" for:
http://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/12month/
http://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/overall/

for II: e.g. for your user account it seems to work:
http://sean.mcgivern.me.uk/last-fm-music-mapper/:smcgivern/12month/

**Comment by smcgivern** [comment]
I think this is an encoding issue. It appears to be a problem with Angela Zhang, who gets this name somehow in an artist record on Last.fm:
http://www.last.fm/music/%C3%95%C3%A5%C3%A9%C3%B8%C2%BA%C2%AD

This gets changed by Addressable to:
http://ws.audioscrobbler.com/2.0/?method=artist.gettoptags&api_key=blah&format=json&artist=%C3%95%C3%A5%C3%A9%C3%B8o%C2%AD

Notice how `%C2%BA` has been replaced by `o`, which isn't a valid artist with Last.fm. Digging into this further would take a while, as this still runs on Ruby 1.8 (!) and I don't have a proper dev environment set up for that at the moment. If I just ignored this artist, would that work for you?

**Comment by Erkan-Yilmaz** [comment]
yes, ignoring would be OK for now

**Comment by smcgivern** [comment]
Cool, this should work now:
http://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/12month/

For the overall one, I get a 500 response from the Last.fm API, which I'll have to look into further when I have time.

**Comment by Erkan-Yilmaz** [comment]
ok, thx so far

**Comment by smcgivern** [comment]
This is a very late and somewhat [CADT] response, but: https://sean.mcgivern.me.uk/last-fm-music-mapper/:Erkan-Yilmaz/overall/ now seems to work for me. (I just rewrote this project in a different programming language, which may handle Unicode better, but that doesn't explain the 500 I was getting from the Last.fm API that I don't get any more.)

[CADT]: https://www.jwz.org/doc/cadt.html
